name: howler
description: Audio library for the modern web. This makes working with audio in Dart easy and reliable across many platforms. (Port of howler.js to Dart)
version: 1.0.3
homepage: https://github.com/gmpassos/howler.dart
author: Graciliano M. Passos <gracilianomp@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 swiss_knife: ^2.0.0


dev_dependencies:
  test: ^1.5.1
